---
title: 'Social Media Analytics'
subtitle: "Writing the introduction and method section"
output:
  html_document:
    theme: united
    highlight: tango
    css: custom.css
    toc: true
    toc_depth: 2
editor_options:
  chunk_output_type: console
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```

# This document

Your final assignment in P6 is to write a research report, for which you'll work through a full research cycle of coming up with a research question, collecting the data, performing the analysis, and drawing conclusions. 
Each week you'll write one of these components, and every Monday you'll meet up with you supervisor to discuss progress and ask questions.
At the end of the second week, you have to submit a draft version of the introduction and method section.
In this document, we provide more detailed guidelines for how to appraoch these sections.

All research papers share a common structure, usually revolving around the sections: introduction, literature overview, method, results, conclusion/discussion. But there are some variations to this theme, relating to the field of research (e.g., media psychology, political communication, marketing, corporate communication) and methodology (e.g., experiment, survey, content analysis).
In the project in P6, you will conduct a content analysis of social media data, and you will learn what the key components of a research report are in a content analysis study.
We focus less on literature and more on method, in line with the more methodological focus of this course.
In this document we'll dedicate our attention to the introduction and method section. 

# The introduction section

In the introduction section you need to explain to the reader what your study is all about. Although there is quite some freedom in how to approach this, there are some common components that need to be in there. For your research report, the following components are most important. 

### Introduce the topic
Start the introduction with a short lead in which you introduce the main topic. Don't just start with: "in this study we investigate ...", but pull your reader in first. For example, imagin that your study is about [the debate on April 1 about the leaked notes from the Dutch cabinet formation process](https://nltimes.nl/2021/04/02/pm-rutte-survives-debate-formation-leak-image-severely-damaged), and how this affected public opinion about Mark Rutte. Your first paragraph should then convince your reader that this was indeed a key debate for Mark Rutte, and well worth investigating. In that sense it could be similar to the first paragraph of the news article.

### Research question
A study should have a clear overarching question. The main purpose of this question is to help your readers understand what they will learn by reading your report, as well as help yourself focus in writing the report. 

Writing a good question is a bit of an art, but there are [some guidelines](https://writingcenter.gmu.edu/guides/how-to-write-a-research-question). 
An important thing to keep in mind is that this overarching research question is broader then the specific questions that you answer in your analysis (this is what the (sub)questions and hypotheses are for). 

For example, a paper might say: "In this study we investigate how the parliamentary debate about the leaked notes from the Dutch cabinet formation process affected public opinion of Mark Rutte". 
This makes it sufficiently clear what the main goal of the paper is.
It doesn't yet have to specify how this study contributes to answering this question.
Later on you can clarify that you analyze public opinion based on how people talk on Twitter, and that you mainly focus on whether people are positive or negative (which tells us something, but certainly not everything, about public opinion).
In short, the research question should clearly communicate the main goal of the study, but doesn't yet have to contain all the details. 

### Method
The introduction section should also mention the method.
This shouldn't yet contain the details (that's what the method section is for), but it should clarify your general approach.
You first of all want to mention the type of research method (content analysis, experiment, survey, interview, etc.).
In this project, you'll want to specify that you used content analysis (as opposed to an experiment, survey, etc.), and more specifically automatic content analysis (as opposed to manual content analysis).
Since we use content analysis, you should mention what content you analyze (e.g. tweets about Mark Rutte within a week before and after the debate), and what the main concepts are that you'll be measuring (e.g., sentiment and topics). 
Note that you can often summarize this key information quite compactly: "we used automatic content analysis to analyze the sentiment and topics of tweets about Mark Rutte in one week before and after the debate".

The hard part (again) is to distinguish key information from details.
For instance, you should mention that you used social media data, but you don't yet have to explain how you got it (e.g., via OBI4wan), and you certainly shouldn't yet mention the specific query that you used.
You should mention what types techniques you use (e.g., topic modeling, dictionary), and you can be somewhat specific (e.g., that you use the STM topic model, or NRC sentiment dictionary), but you don't describe specific choices (e.g., whether you used stemming).

Finally, it is often good to say something about why this method makes sense for this study. 
Different methods have different pro's and con's, and you might want to spend a sentence or two to convince your reader of why your method is a good choice.
For instance, if you study public opinion using a sentiment analysis on Twitter, you could refer to other studies that have done something similar (tip: search on Google Scholar for `twitter public opinion analysis`)

All of this typically goes into a single paragraph, so keep it snappy, and think hard on what they key information is.

### Relevance
It should be explained why the study is relevant (even if you think the relevance is obvious). In scientific studies relevance is typically theoretical and/or societal. But research can also serve a more practical purpose, for instance for a specific organization. For the final assignment you are allowed to choose whether you focus more theoretical, societal or practical relevance, and you can pretend that this is a study performed for a certain organization (e.g., a company, NGO, political party). 

Also, you don't have to worry much about novelty for this assignment (as will for instance be a criterion for your master thesis). You don't have to search for 'holes' in the literature, and it's not a problem if your study addresses a very similar question as an existing study. 


### Questions and hypotheses
The overarching research question is typically very broad, so researchers formulate more specific (sub)questions to answer and hypotheses to test. For example, to investigate how the debate might have affected how people think and talk about Mark Rutte, we can more specifically measure: `(RQ1) What are the main topics of Twitter messages about Mark Rutte in the week following the debate`. We can also formulate very specific hypotheses about how the way people talk about Mark Rutte on Twitter changes due to the debate. Based on theory (and a bit of common knowledge), we can expect that `(H1) Tweets about Mark Rutte one week after the debate are on average more negative compared to one week before the debate`.

Normally these are often formulated in a separate **theory** (or literature) section, but for the final assignment you won't have to write an extensive theory section, and can include the questions/hypotheses in the introduction. We strongly advise formulating at least one explorative question, and one hypothesis. 


> Note that you are required to use academic literature (at least 5 papers or books). The most obvious parts of the introduction to include this are the *relevance* and *questions / hypotheses*. You can also refer to sources about methodological techniques, such as providing a reference for Structural Topic Models (if you use them), or studies that argue how social media analytics can be used to study public opinion.


# The Method section

Where the introduction section has a more creative touch to it (it needs to both inform and pull in the reader) the method section is generally more structured and rigid. One of the most important goals of the method section is transparency and reproducibility. Simply put, it should provide the information that other researcher would need to replicate your study. 

Importantly, you should focus on describing what you did, but you should not describe in extreme detail `how` you did it. 
In particular, you should describe the method, and not the specific tool that you used.
This also means that you should not discuss R in your methods section (you will include your R code in the appendix). 
For example, if you use Topic Modeling you SHOULD say whether or not you applied stemming, but you should NOT say that you used the `dfm_wordstem` to do this. 

For the final assignment, we strongly recommend dividing the method section into three subsection: *data*, *content analysis*, and *validation*. 

### Data

In the data subsection you very clearly describe what data you use. 

* Where you got the data from (OBI4wan)
* What time period 
* What sources (we recommend just using Twitter)
* What query you used. (report the EXACT query. If its super long, you can put in the appendix). 
* If you had to take a sample, you should mention how you did this. Remember that you can only download 20.000 messages from OBI4wan at a time. You can quite easily separate your data into multiple smaller time periods to collect more (as we did in the fourth practical), but there are still limits. If you find more than 100.000 tweets, you are allowed to take a sample.
* What is the total number of messages in your data

### Content analysis

In the `content analysis` section, you need to explain how you have actually measured the abstract concepts that you used in your questions and/or hypotheses.
Take the following hypothesis: `Tweets about Mark Rutte one week after the debate are on average more negative compared to one week before the debate`.
The abstract concept here is "more negative".
To test this hypothesis, you need to describe how you turn this abstract concept into something that you can measure.
This process is also called operationalization. 

The first step here is to clarify what "more negative" means to the researcher. 
For instance, does this mean that people are negative *about* Mark Rutte himself? Or is something like "ahh, poor Mark Rutte" also negative?
The second step is to describe what technique the researcher will use to measure this. 
If any kind of negative emotion will do, then a sentiment dictionary might be a viable option. But if we're specifically interested in whether the author of a message voices a negative opinion about Mark Rutte, then we might need a more sophisticated tool that can distinguish to whom negative sentiment is targeted. We could still use a sentiment dictionary, but we might then find many false positives like "It was a terrible day for Mark Rutte". 
By clearly relating what you're trying to measure to what measurement technique you use, your reader can better understand (and judge the validity of) your analysis.

Note that sometimes the question or hypothesis already mentions how you measure something, but that doesn't mean that you're not interested in measuring some more abstract concept. For example, you might have a question about how much the number of tweets about a company increased after launching a certain campaign. But in this case you're probably not actually interested in the number of tweets, but rather what this tells you about public interest in the company. So even if it might feel obvious, you should make sure that you distinguish what you're substantively interested in from how you measure it.


> Tip: Thinking about operationalization can also help you develop research questions and hypotheses. Not all abstract concepts that we can think of can be turned into measurable observations, so when we design a study we also need to think the other way around: given the measurable observations that we can obtain, what abstract concepts can we actually measure? For the final assignment, you should think hard on what techniques you now learned in this course for performing certain measurements, and how this let's you answer certain types of questions and test certain types of hypotheses.   


### Validity

Validation is the logical next step after operationalization.
Above you clarified how you're going to measure certain abstract concepts.
In the validation section, you're going to show how good these measurements really are.
Very concretely, what this means is that you're going to calculate precision and recall scores.

Now, we won't ask you to validate EVERYTHING, and we'll also keep the amount of messages that you need to manually code moderate. 
The reason is simply that doing manual coding for validation is time-consuming, and we would rather have you direct your energy elsewhere. 
However, we do emphasize that in a proper study validation should not be skipped, and when you read a research report with an automatic content analysis component you should always read the validation section (or worry when it's absent).

Specifically, you'll need to perform two separate precision and recall measurements in your final paper[^1].

[^1]: It might happen that in your final assignment you perform your validation, and come to the conclusion that your measurement is pretty much useless. 
This doesn't automatically mean that you did something wrong, and you won't have to redo everything. 
An important learning goal of this course is to realize that the validity of a (computational) measurement should never be taken for granted.
It can always mess up, and should always be tested.
Normally, finding out that your precision and recall are not good enough would mean that you'd have to go back to the drawing board to improve your measurement tool or forfeit your study, but for this assignment this is certainly not required.
Even if your precision and recall turn out to be hilariously low, you can simply continue with your study as if nothing is amiss. 
You will be graded on how well you demonstrate your understanding of how to conduct good research, and good researchers can still end up with cases of low precision.
What matters is that you show us that you understand the limitations of your study, which you can do in the `reflection` section of the assignment.

* You need to perform a precision and recall measurement for `the most important measurement` in your study (discuss with your supervisor if it's not clear which measurement this is). For example, if your main question or hypothesis is based on sentiment analysis, then perform the P&R measurement for this sentiment analysis. For this measurement every team-member should manually code 50 messages (so with 5 members, you'd end up with a gold standard of 250 messages). 
* You need to perform a precision measurement (no recall) for your **population query**. That is, the query that you use in OBI4wan to retrieve the messages. Here you manually code 100 random messages from the OBI4wan results to calculate the precision. (this is the same calculation as you used in assignment 2.d of the 2nd practical)


